name: macOS Combined Chez

on:
  workflow_run:
    workflows: ["Quick check"]
    types:
      - completed

env:
  SCHEME: chez

jobs:

  # Building the executable

  build-bootstrap-chez:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build dependencies
        run: |
          brew install chezscheme
          brew install coreutils
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
      - name: Build Idris 2 from bootstrap
        run: make bootstrap && make install
        shell: bash
      - name: Artifact Bootstrapped Idris2
        uses: actions/upload-artifact@v2
        with:
          name: installed-bootstrapped-idris2-chez
          path: ~/.idris2/

  # self hosting and testing

  self-host-chez:
    needs: build-bootstrap-chez
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Idris2 Artifact
        uses: actions/download-artifact@v2
        with:
          name: installed-bootstrapped-idris2-chez
          path: ~/.idris2/
      - name: Install build dependencies
        run: |
          brew install chezscheme
          brew install coreutils
          echo "$HOME/.idris2/bin" >> $GITHUB_PATH
          chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*
      - name: Build self-hosted
        run: make all IDRIS2_BOOT="idris2 -Werror" && make install
        shell: bash
      - name: Test self-hosted
        run: make test INTERACTIVE=''
        shell: bash

  # this gambit test is really slow so se run it separately

  # test-gambit:
  #   needs: build-bootstrap-chez
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Download Idris2 Artifact
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: installed-bootstrapped-idris2-chez
  #         path: ~/.idris2/
  #     - name: Install build dependencies
  #       run: |
  #         brew install chezscheme
  #         brew install coreutils
  #         brew install gambit-scheme
  #         CURRENTDIR=$(find /usr/local/Cellar/gambit-scheme -type l -name current)
  #         echo "::add-path::${CURRENTDIR}/bin"
  #         echo "$HOME/.idris2/bin" >> $GITHUB_PATH
  #         chmod +x $HOME/.idris2/bin/idris2 $HOME/.idris2/bin/idris2_app/*
  #     - name: Test gambit
  #       run: cd tests/gambit/bitops001/ && ./run idris2
  #       shell: bash
